# Generated by Django 4.0.1 on 2022-04-09 23:37

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event/default.jpg', upload_to=event.models.upload_to),
        ),
    ]
