# Generated by Django 4.0.1 on 2022-04-09 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import venues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip', models.IntegerField(null=True)),
                ('has_nft', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='venue/default.jpg', upload_to=venues.models.upload_to)),
                ('published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
