# Generated by Django 4.0.1 on 2022-01-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venues',
            new_name='Venue',
        ),
    ]
