# Generated by Django 4.0.1 on 2022-02-09 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0002_rename_venues_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_nft',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='zip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
