# Generated by Django 4.0.1 on 2022-02-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_enduserfavoritelist_venues'),
        ('venues', '0005_venue_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='enduserfavoriteList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.enduserfavoritelist'),
        ),
    ]
