# Generated by Django 4.0.1 on 2022-04-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venue_enduserfavoritelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='enduserfavoriteList',
        ),
    ]
