# Generated by Django 4.0.1 on 2022-04-09 23:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='userProfile/default.jpg', upload_to=users.models.upload_to),
        ),
    ]
