# Generated by Django 4.0.1 on 2022-02-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_enduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='endUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
