# Generated by Django 4.0.1 on 2022-02-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_enduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduserfavoritelist',
            name='endUser',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='endUser',
        ),
        migrations.DeleteModel(
            name='EndUserCreatedVenues',
        ),
        migrations.DeleteModel(
            name='EndUserFavoriteList',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
