# Generated by Django 4.0.1 on 2022-02-10 07:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_enduserfavoritelist_enduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip', models.IntegerField(default=11111, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('endUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
