# Generated by Django 4.0.1 on 2022-02-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_venue_created_by'),
        ('users', '0007_enduserfavoritelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserfavoritelist',
            name='venues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venues.venue'),
        ),
    ]
