# Generated by Django 4.0.1 on 2022-02-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_enduserfavoritelist_venues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduserfavoritelist',
            name='venues',
        ),
    ]
