# Generated by Django 4.0.1 on 2022-04-04 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_enduserfavoritelist_venues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndUserFavoriteList',
            new_name='EndUserCreatedVenues',
        ),
        migrations.CreateModel(
            name='EndUserVenueFavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
