# Generated by Django 4.0.1 on 2022-04-05 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('venues', '0007_remove_venue_enduserfavoritelist'),
        ('users', '0010_rename_enduserfavoritelist_endusercreatedvenues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserEventsFavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(to='event.Event')),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='enduservenuefavoritelist',
            name='endUser',
        ),
        migrations.AddField(
            model_name='enduservenuefavoritelist',
            name='userProfile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='enduservenuefavoritelist',
            name='venues',
            field=models.ManyToManyField(to='venues.Venue'),
        ),
        migrations.DeleteModel(
            name='EndUserCreatedVenues',
        ),
    ]
